name_of_the_researcher = input('Введите ФИО исследователя: ')
date = input('Введите дату проведения эксперимента: ')
name_of_the_expriment = input('Введите название эксперимента: ')
conclusion = input('Вывод по работе: ')
with open('journal.txt', 'w', encoding='utf-8') as lab:
    lab.write('+------------------------------------------------+\n')
    lab.write(f'| Электроный лабораторный журнал                 |\n')
    lab.write('+------------------------------------------------+\n')
    lab.write(f'| ФИО исследователя: {name_of_the_researcher}    |\n')
    lab.write(f'| Дата             : {date}                      |\n')
    lab.write(f'| Эксперимент      : {name_of_the_expriment}     |\n')
    lab.write('+------------------------------------------------+\n')
    lab.write(f'| Вывод      : {conclusion}                      |\n')
    lab.write(f'|                                                |\n')
    lab.write('+------------------------------------------------+\n')